pipeline {
    agent any
    options {
        skipDefaultCheckout true
        parallelsAlwaysFailFast()
    }

    stages {
        stage('Checkout') {
            steps {
                dir('build-folder') {
                    deleteDir()
                }
                dir('test-ui-folder') {
                    deleteDir()
                }
                dir('build-folder') {
                    git branch: "master",
                            url: 'https://github.com/igor-dmitriev/spring-petclinic-reactjs-ui-tests.git'

                }
                dir('test-ui-folder') {
                    git branch: "master",
                            url: 'https://github.com/igor-dmitriev/spring-petclinic-reactjs-ui-tests.git'
                }

            }
        }

        stage('Run build and testUi in parallel') {
            parallel {
                stage('Build') {
                    steps {
                        sh 'cd build-folder && ./gradlew clean build --info'

                    }
                }

                stage('Test UI') {
                    steps {
                        sh 'cd test-ui-folder && ./gradlew clean testUi --info'

                    }
                }

            }
        }
    }

    post {
        always {
            archiveArtifacts allowEmptyArchive: false,
                    artifacts: '**/build/**',
                    caseSensitive: true,
                    defaultExcludes: true,
                    fingerprint: false,
                    onlyIfSuccessful: false
        }
    }
}